'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class barcode_data
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sku_Scaner.barcode_data", GetType(barcode_data).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        '''  재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  8809800940408과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10103R() As String
            Get
                Return ResourceManager.GetString("10103R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809689373915과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10107R() As String
            Get
                Return ResourceManager.GetString("10107R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10108R() As String
            Get
                Return ResourceManager.GetString("10108R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809686389872과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10111R() As String
            Get
                Return ResourceManager.GetString("10111R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940453과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10112R() As String
            Get
                Return ResourceManager.GetString("10112R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940255과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10114R() As String
            Get
                Return ResourceManager.GetString("10114R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809782555614과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10116R() As String
            Get
                Return ResourceManager.GetString("10116R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940262과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10117R() As String
            Get
                Return ResourceManager.GetString("10117R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940651과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10118R() As String
            Get
                Return ResourceManager.GetString("10118R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940682과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10119R() As String
            Get
                Return ResourceManager.GetString("10119R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940941과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10120R() As String
            Get
                Return ResourceManager.GetString("10120R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10121R() As String
            Get
                Return ResourceManager.GetString("10121R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941030과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10122R() As String
            Get
                Return ResourceManager.GetString("10122R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809541199813과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10202R() As String
            Get
                Return ResourceManager.GetString("10202R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940286과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10203R() As String
            Get
                Return ResourceManager.GetString("10203R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940279과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10204R() As String
            Get
                Return ResourceManager.GetString("10204R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940323과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10205R() As String
            Get
                Return ResourceManager.GetString("10205R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940361과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10206R() As String
            Get
                Return ResourceManager.GetString("10206R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10207R() As String
            Get
                Return ResourceManager.GetString("10207R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940330과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10302R() As String
            Get
                Return ResourceManager.GetString("10302R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940316과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10304R() As String
            Get
                Return ResourceManager.GetString("10304R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940378과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10305R() As String
            Get
                Return ResourceManager.GetString("10305R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809088970395과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10601R() As String
            Get
                Return ResourceManager.GetString("10601R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809088970357과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10602R() As String
            Get
                Return ResourceManager.GetString("10602R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8806135250219과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10801R() As String
            Get
                Return ResourceManager.GetString("10801R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940293과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _10802R() As String
            Get
                Return ResourceManager.GetString("10802R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940309과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11003R() As String
            Get
                Return ResourceManager.GetString("11003R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940477과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11005R() As String
            Get
                Return ResourceManager.GetString("11005R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940491과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11006R() As String
            Get
                Return ResourceManager.GetString("11006R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940385과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11008R() As String
            Get
                Return ResourceManager.GetString("11008R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940972과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11010R() As String
            Get
                Return ResourceManager.GetString("11010R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940965과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11012R() As String
            Get
                Return ResourceManager.GetString("11012R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940170과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11201R() As String
            Get
                Return ResourceManager.GetString("11201R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940835과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11202R() As String
            Get
                Return ResourceManager.GetString("11202R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940859과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11203R() As String
            Get
                Return ResourceManager.GetString("11203R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940866과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11204R() As String
            Get
                Return ResourceManager.GetString("11204R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11205R() As String
            Get
                Return ResourceManager.GetString("11205R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11206R() As String
            Get
                Return ResourceManager.GetString("11206R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940804과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11207R() As String
            Get
                Return ResourceManager.GetString("11207R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940910과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11208R() As String
            Get
                Return ResourceManager.GetString("11208R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11212R() As String
            Get
                Return ResourceManager.GetString("11212R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941061과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11214R() As String
            Get
                Return ResourceManager.GetString("11214R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11215R() As String
            Get
                Return ResourceManager.GetString("11215R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941269과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11217R() As String
            Get
                Return ResourceManager.GetString("11217R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941214과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _11218R() As String
            Get
                Return ResourceManager.GetString("11218R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809686383559과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20101R() As String
            Get
                Return ResourceManager.GetString("20101R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809581076341과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20103R() As String
            Get
                Return ResourceManager.GetString("20103R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809474498151과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20104R() As String
            Get
                Return ResourceManager.GetString("20104R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809686389391과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20105() As String
            Get
                Return ResourceManager.GetString("20105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809686389391과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20105R() As String
            Get
                Return ResourceManager.GetString("20105R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809540517533과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20106R() As String
            Get
                Return ResourceManager.GetString("20106R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809540517540과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20107R() As String
            Get
                Return ResourceManager.GetString("20107R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20108R() As String
            Get
                Return ResourceManager.GetString("20108R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809540517557과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20109R() As String
            Get
                Return ResourceManager.GetString("20109R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809626566431과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20110R() As String
            Get
                Return ResourceManager.GetString("20110R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20111R() As String
            Get
                Return ResourceManager.GetString("20111R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20113R() As String
            Get
                Return ResourceManager.GetString("20113R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809686384228과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20114R() As String
            Get
                Return ResourceManager.GetString("20114R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20115R() As String
            Get
                Return ResourceManager.GetString("20115R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809686384204과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20116R() As String
            Get
                Return ResourceManager.GetString("20116R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809686383566과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20117R() As String
            Get
                Return ResourceManager.GetString("20117R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20118R() As String
            Get
                Return ResourceManager.GetString("20118R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20119R() As String
            Get
                Return ResourceManager.GetString("20119R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809782554464과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20125R() As String
            Get
                Return ResourceManager.GetString("20125R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940637과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20126R() As String
            Get
                Return ResourceManager.GetString("20126R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940644과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20127R() As String
            Get
                Return ResourceManager.GetString("20127R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940668과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20128R() As String
            Get
                Return ResourceManager.GetString("20128R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940675과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20129R() As String
            Get
                Return ResourceManager.GetString("20129R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940743과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20130R() As String
            Get
                Return ResourceManager.GetString("20130R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940743과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20130RR() As String
            Get
                Return ResourceManager.GetString("20130RR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20131R() As String
            Get
                Return ResourceManager.GetString("20131R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20132R() As String
            Get
                Return ResourceManager.GetString("20132R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941252과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20133R() As String
            Get
                Return ResourceManager.GetString("20133R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809541190421과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20202R() As String
            Get
                Return ResourceManager.GetString("20202R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20203R() As String
            Get
                Return ResourceManager.GetString("20203R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809541190254과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20204R() As String
            Get
                Return ResourceManager.GetString("20204R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809738322154과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20205R() As String
            Get
                Return ResourceManager.GetString("20205R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809738592236과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20206R() As String
            Get
                Return ResourceManager.GetString("20206R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940194과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20302R() As String
            Get
                Return ResourceManager.GetString("20302R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940187과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20304R() As String
            Get
                Return ResourceManager.GetString("20304R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940224과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20305R() As String
            Get
                Return ResourceManager.GetString("20305R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940231과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20306R() As String
            Get
                Return ResourceManager.GetString("20306R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940163과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20309R() As String
            Get
                Return ResourceManager.GetString("20309R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940200과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20310R() As String
            Get
                Return ResourceManager.GetString("20310R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20311R() As String
            Get
                Return ResourceManager.GetString("20311R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940217과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20313R() As String
            Get
                Return ResourceManager.GetString("20313R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941245과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20314R() As String
            Get
                Return ResourceManager.GetString("20314R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941290과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20316R() As String
            Get
                Return ResourceManager.GetString("20316R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809541190438과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20405R() As String
            Get
                Return ResourceManager.GetString("20405R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809541190247과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20406R() As String
            Get
                Return ResourceManager.GetString("20406R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940699과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20407R() As String
            Get
                Return ResourceManager.GetString("20407R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809236798093과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20408R() As String
            Get
                Return ResourceManager.GetString("20408R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940156과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20601R() As String
            Get
                Return ResourceManager.GetString("20601R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940149과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20602R() As String
            Get
                Return ResourceManager.GetString("20602R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940132과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20604R() As String
            Get
                Return ResourceManager.GetString("20604R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809783322666과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20605R() As String
            Get
                Return ResourceManager.GetString("20605R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940606과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20606R() As String
            Get
                Return ResourceManager.GetString("20606R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809187049350과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20701R() As String
            Get
                Return ResourceManager.GetString("20701R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809187049428과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20703R() As String
            Get
                Return ResourceManager.GetString("20703R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8806135244911과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20801R() As String
            Get
                Return ResourceManager.GetString("20801R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20802R() As String
            Get
                Return ResourceManager.GetString("20802R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8806135245765과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20803R() As String
            Get
                Return ResourceManager.GetString("20803R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20804R() As String
            Get
                Return ResourceManager.GetString("20804R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809581076334과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20902R() As String
            Get
                Return ResourceManager.GetString("20902R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940101과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20906R() As String
            Get
                Return ResourceManager.GetString("20906R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940118과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _20907R() As String
            Get
                Return ResourceManager.GetString("20907R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809783322642과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21001() As String
            Get
                Return ResourceManager.GetString("21001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809783322642과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21001R() As String
            Get
                Return ResourceManager.GetString("21001R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809783322659과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21002R() As String
            Get
                Return ResourceManager.GetString("21002R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809783322635과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21003R() As String
            Get
                Return ResourceManager.GetString("21003R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940460과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21005R() As String
            Get
                Return ResourceManager.GetString("21005R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940712과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21008R() As String
            Get
                Return ResourceManager.GetString("21008R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940736과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21009R() As String
            Get
                Return ResourceManager.GetString("21009R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940729과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21010R() As String
            Get
                Return ResourceManager.GetString("21010R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940767과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21011R() As String
            Get
                Return ResourceManager.GetString("21011R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940767과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21011RR() As String
            Get
                Return ResourceManager.GetString("21011RR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941047과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21012R() As String
            Get
                Return ResourceManager.GetString("21012R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941078과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21013R() As String
            Get
                Return ResourceManager.GetString("21013R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21014R() As String
            Get
                Return ResourceManager.GetString("21014R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941221과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21017R() As String
            Get
                Return ResourceManager.GetString("21017R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941238과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21018R() As String
            Get
                Return ResourceManager.GetString("21018R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940057과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21101R() As String
            Get
                Return ResourceManager.GetString("21101R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940125과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21201R() As String
            Get
                Return ResourceManager.GetString("21201R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940514과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21202R() As String
            Get
                Return ResourceManager.GetString("21202R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940521과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21203R() As String
            Get
                Return ResourceManager.GetString("21203R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940750과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21204R() As String
            Get
                Return ResourceManager.GetString("21204R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940750과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21204RR() As String
            Get
                Return ResourceManager.GetString("21204RR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21205R() As String
            Get
                Return ResourceManager.GetString("21205R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940774과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21301R() As String
            Get
                Return ResourceManager.GetString("21301R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940798과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21302R() As String
            Get
                Return ResourceManager.GetString("21302R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940781과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21303R() As String
            Get
                Return ResourceManager.GetString("21303R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940880과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21304R() As String
            Get
                Return ResourceManager.GetString("21304R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941160과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _21305R() As String
            Get
                Return ResourceManager.GetString("21305R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809236799076과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30081() As String
            Get
                Return ResourceManager.GetString("30081", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940088과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30310() As String
            Get
                Return ResourceManager.GetString("30310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940507과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30313() As String
            Get
                Return ResourceManager.GetString("30313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30314() As String
            Get
                Return ResourceManager.GetString("30314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30315() As String
            Get
                Return ResourceManager.GetString("30315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30317() As String
            Get
                Return ResourceManager.GetString("30317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940620과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30318() As String
            Get
                Return ResourceManager.GetString("30318", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30319() As String
            Get
                Return ResourceManager.GetString("30319", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30320() As String
            Get
                Return ResourceManager.GetString("30320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940842과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30322() As String
            Get
                Return ResourceManager.GetString("30322", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800940989과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30324() As String
            Get
                Return ResourceManager.GetString("30324", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30325() As String
            Get
                Return ResourceManager.GetString("30325", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30326() As String
            Get
                Return ResourceManager.GetString("30326", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941016과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30327() As String
            Get
                Return ResourceManager.GetString("30327", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941023과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30328() As String
            Get
                Return ResourceManager.GetString("30328", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30330() As String
            Get
                Return ResourceManager.GetString("30330", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  8809800941276과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _30331() As String
            Get
                Return ResourceManager.GetString("30331", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
